language: java
jdk: oraclejdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: required
services:
  - docker

script:
  - mvn test
  - docker build --tag pangolin .
  - docker run pangolin
